### ISSUE TITLE
[Task] HTML 'canvas' 요소 공부

### ISSUE THREAD

**Issue by shren207** [shren207/we-ar#3]
### TODO
 - [x] MDN에서 공부 (https://developer.mozilla.org/ko/docs/Games/Tutorials/2D_Breakout_game_pure_JavaScript)
   - [x] 1. `Create the Canvas and draw on it` 학습
   - [x] 2. `Move the ball` 학습
   - [x] 3. `Bounce off the walls` 학습
 - [x] `requestAnimationFrame` 공부
